#!/usr/bin/env ruby

git_bundles = [
  "git://github.com/astashov/vim-ruby-debugger.git",
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/timcharper/textile.vim.git",
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tpope/vim-vividchalk.git",
  "http://github.com/tpope/vim-unimpaired.git",
  "git://github.com/tsaleh/vim-align.git",
  "git://github.com/tsaleh/vim-shoulda.git",
  "git://github.com/tsaleh/vim-tcomment.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  "https://github.com/scrooloose/syntastic.git",
  "http://github.com/vim-scripts/matchit.zip.git",
  "http://github.com/vim-scripts/taglist.vim.git",
  "http://github.com/vimoutliner/vimoutliner.git",
  "https://github.com/vim-scripts/L9.git",
  "https://github.com/vim-scripts/FuzzyFinder.git",
  "https://github.com/vim-scripts/Conque-Shell.git",
  "https://github.com/altercation/vim-colors-solarized.git",
  "https://github.com/vim-scripts/bufferlist.vim.git",
  "https://github.com/gregsexton/gitv.git",
  "https://github.com/kchmck/vim-coffee-script.git",
  "https://github.com/mileszs/ack.vim.git",
  "https://github.com/aniero/vim-copy-as-rtf.git",
  "https://github.com/tangledhelix/vim-octopress.git"
  "https://github.com/Lokaltog/vim-powerline.git",
  "https://github.com/kien/ctrlp.vim.git"
]

vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
  ["jquery",        "12107", "syntax"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.mkdir_p bundles_dir
FileUtils.cd(bundles_dir)

#puts "Trashing everything (lookout!)"
#Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')

  puts "  Unpacking #{url} into #{dir}"
  if File.exist? dir
    puts `cd #{dir} && git pull`
  else
    puts `git clone #{url} #{dir}`
  end
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end

# update helptags
Dir["*/doc"].map { |dir| %Q[-c "helptags #{dir}"]}.each_slice(8) do |params|
  puts %Q[vim #{params.join(' ')} -c"quit"]
  `vim #{params.join(' ')} -c"quit"`
end
