#!/usr/bin/env ruby

git_bundles = [
  "git://github.com/astashov/vim-ruby-debugger.git",
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/timcharper/textile.vim.git",
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tpope/vim-vividchalk.git",
  "http://github.com/tpope/vim-unimpaired.git",
  "git://github.com/tsaleh/vim-align.git",
  "git://github.com/tsaleh/vim-shoulda.git",
  "https://github.com/vim-scripts/tComment.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  "https://github.com/scrooloose/syntastic.git",
  "http://github.com/vim-scripts/matchit.zip.git",
  "http://github.com/vimoutliner/vimoutliner.git",
  "https://github.com/vim-scripts/Conque-Shell.git",
  "https://github.com/altercation/vim-colors-solarized.git",
  "https://github.com/gregsexton/gitv.git",
  "https://github.com/kchmck/vim-coffee-script.git",
  "https://github.com/mileszs/ack.vim.git",
  "https://github.com/aniero/vim-copy-as-rtf.git",
  "https://github.com/tangledhelix/vim-octopress.git",
  "https://github.com/Lokaltog/vim-powerline.git",
  "https://github.com/kien/ctrlp.vim.git",
  "https://github.com/timgreen/vim-tagbar.git",
  "https://github.com/henrik/vim-indexed-search.git",
  "https://github.com/nono/jquery.vim"
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.mkdir_p bundles_dir
FileUtils.cd(bundles_dir)

#puts "Trashing everything (lookout!)"
#Dir["*"].each {|d| FileUtils.rm_rf d }

all_dirs = Dir['*']

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')

	all_dirs.delete dir
  puts "  Unpacking #{url} into #{dir}"
  if File.exist? dir
    puts `cd #{dir} && git pull`
  else
    puts `git clone #{url} #{dir}`
  end
end

all_dirs.each do |dir|
  puts "  Remove unused dir #{dir}"
  FileUtils.rm_rf dir
end

# update helptags
Dir["*/doc"].map { |dir| %Q[-c "helptags #{dir}"]}.each_slice(8) do |params|
  puts %Q[vim #{params.join(' ')} -c"quit"]
  `vim #{params.join(' ')} -c"quit"`
end
